// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWCjofaUybd5NisJ3-pFSoKQp712GapXs',
    appId: '1:652884480519:web:45b5acae820825f97f50a2',
    messagingSenderId: '652884480519',
    projectId: 'nominapp-6e1b3',
    authDomain: 'nominapp-6e1b3.firebaseapp.com',
    storageBucket: 'nominapp-6e1b3.firebasestorage.app',
    measurementId: 'G-R60V6ML8H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcnf8AP-v6VZIZfwgn4mXyCzoaFDhGOFY',
    appId: '1:652884480519:android:b85e04e8823c57c27f50a2',
    messagingSenderId: '652884480519',
    projectId: 'nominapp-6e1b3',
    storageBucket: 'nominapp-6e1b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvrNJVHxKCZMnzE52NwKHXuwoAORrxDgc',
    appId: '1:652884480519:ios:7ea9f1b1cb78e7a77f50a2',
    messagingSenderId: '652884480519',
    projectId: 'nominapp-6e1b3',
    storageBucket: 'nominapp-6e1b3.firebasestorage.app',
    iosBundleId: 'com.example.nominappT2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvrNJVHxKCZMnzE52NwKHXuwoAORrxDgc',
    appId: '1:652884480519:ios:7ea9f1b1cb78e7a77f50a2',
    messagingSenderId: '652884480519',
    projectId: 'nominapp-6e1b3',
    storageBucket: 'nominapp-6e1b3.firebasestorage.app',
    iosBundleId: 'com.example.nominappT2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWCjofaUybd5NisJ3-pFSoKQp712GapXs',
    appId: '1:652884480519:web:1296fe24adfa15997f50a2',
    messagingSenderId: '652884480519',
    projectId: 'nominapp-6e1b3',
    authDomain: 'nominapp-6e1b3.firebaseapp.com',
    storageBucket: 'nominapp-6e1b3.firebasestorage.app',
    measurementId: 'G-RR5FG5TBNP',
  );
}
